#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: hbpneurorobotics/nrp_frontend:dev
pipelines:
  branches:
    development:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - sudo apt-get update && sudo apt-get install -y nodejs npm 
            - cp src/mocks/config_test.json src/config.json
            - npm install
            - npm test
            # Coverage check
            - git archive --remote=ssh://git@bitbucket.org/hbpneurorobotics/admin-scripts.git refs/heads/master nrp_cobertura_check | tar xf -
            - ./nrp_cobertura_check reports/coverage/*/cobertura-coverage.xml

      - step:
          name: Code linting
          script:
            - npm install eslint
            - npx eslint .
          caches:
            - node